[2023-11-26T23:08:51.098+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T23:08:45.427523+00:00/task_id=extract permission to 509
[2023-11-26T23:08:51.283+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T23:08:45.427523+00:00/task_id=extract permission to 509
[2023-11-26T23:08:51.400+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.extract manual__2023-11-26T23:08:45.427523+00:00 [queued]>
[2023-11-26T23:08:51.434+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.extract manual__2023-11-26T23:08:45.427523+00:00 [queued]>
[2023-11-26T23:08:51.439+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T23:08:51.868+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2023-11-26 23:08:45.427523+00:00
[2023-11-26T23:08:51.900+0000] {standard_task_runner.py:57} INFO - Started process 121 to run task
[2023-11-26T23:08:51.926+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'extract', 'manual__2023-11-26T23:08:45.427523+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp6s85h1jk']
[2023-11-26T23:08:51.952+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask extract
[2023-11-26T23:08:52.371+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T23:08:45.427523+00:00/task_id=extract permission to 509
[2023-11-26T23:08:52.424+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.extract manual__2023-11-26T23:08:45.427523+00:00 [running]> on host 613ffde293d8
[2023-11-26T23:08:52.870+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T23:08:45.427523+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T23:08:45.427523+00:00'
[2023-11-26T23:08:52.878+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: extract_data() missing 3 required positional arguments: 'source_url', 'gcs_bucket', and 'creds'
[2023-11-26T23:08:52.905+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=extract, execution_date=20231126T230845, start_date=20231126T230851, end_date=20231126T230852
[2023-11-26T23:08:52.961+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task extract (extract_data() missing 3 required positional arguments: 'source_url', 'gcs_bucket', and 'creds'; 121)
[2023-11-26T23:08:53.001+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T23:08:53.189+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
